
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bilal
 */
public class SiparişUygulaması extends javax.swing.JFrame {
    
    Map<String, Integer> siparisler = new LinkedHashMap<>();
    
    /**
     * Creates new form SiparişUygulaması
     */
    public SiparişUygulaması() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kaşarli = new javax.swing.JCheckBox();
        etli = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kuş = new javax.swing.JCheckBox();
        lahmacun = new javax.swing.JCheckBox();
        ez = new javax.swing.JCheckBox();
        köz = new javax.swing.JCheckBox();
        sal = new javax.swing.JCheckBox();
        ayran = new javax.swing.JCheckBox();
        kola = new javax.swing.JCheckBox();
        salgam = new javax.swing.JCheckBox();
        hesapla = new javax.swing.JButton();
        secilen = new javax.swing.JLabel();
        toplam = new javax.swing.JLabel();
        acilirMenü = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("KARDEŞLER PİDE SALONUNA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("HOŞ GELDİNİZ");

        kaşarli.setText("Kaşarlı Pide   (40)");

        etli.setText("Etli Ekmek  (50)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("ANA YEMEKLER");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("MEZELER");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("İÇECEKLER");

        kuş.setText("Kuşbaşı Pide  (40)");
        kuş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuşActionPerformed(evt);
            }
        });

        lahmacun.setText("Lahmacun  (40)");

        ez.setText("Ezme  (30)");
        ez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ezActionPerformed(evt);
            }
        });

        köz.setText("Közlenmiş Patlıcan  (50)");
        köz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                közActionPerformed(evt);
            }
        });

        sal.setText("Salata   (30)");

        ayran.setText("Ayran  (20)");

        kola.setText("Kola   (20)");

        salgam.setText("Şalgam  (20)");

        hesapla.setText("Hesapla");
        hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesaplaActionPerformed(evt);
            }
        });

        secilen.setText("Seçilen Yemekler :");

        toplam.setText("Tutar : ");

        acilirMenü.setText("Açılır Menü Kullan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(acilirMenü))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etli)
                            .addComponent(kaşarli)
                            .addComponent(kuş)
                            .addComponent(lahmacun)
                            .addComponent(hesapla)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toplam, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secilen, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(köz)
                                        .addComponent(ez, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sal, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel4))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ayran)
                                    .addComponent(kola)
                                    .addComponent(salgam)
                                    .addComponent(jLabel5))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kaşarli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kuş))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ez)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(köz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sal))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ayran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salgam)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lahmacun)
                        .addGap(64, 64, 64)
                        .addComponent(hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(secilen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(acilirMenü)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(toplam)
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void EkranaYazdir(){
        
        String yazi1 = " ";
        int tutar = 0;
        
        if (siparisler.isEmpty()){
            JOptionPane.showMessageDialog(this, "Seçim yapınız.");
            secilen.setText("Seçilen Yemekler :");
            toplam.setText("Tutar :");
        }
        else{
            
            for (Map.Entry<String, Integer> entry : siparisler.entrySet()) {
                
                String key = entry.getKey();
                Integer value = entry.getValue();
                
                yazi1 += "->"+key+"\n"; 
                tutar +=  value;
                
                
            secilen.setText("Seçilen Yemekler :"+yazi1);
            toplam.setText("Tutar :"+String.valueOf(tutar));
            }
            yazi1 += "Tutar :" + tutar ;
            
        }
        if (acilirMenü.isSelected()) {
                    JOptionPane.showMessageDialog(this, yazi1);
                }
    }
    
    
    private void kuşActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuşActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kuşActionPerformed

    private void ezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ezActionPerformed

    private void hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesaplaActionPerformed

        if(kaşarli.isSelected()){
            siparisler.put("Kaşarlı Pide", 40);
        }
        else{
            siparisler.remove("Kaşarlı Pide", 40);
        }
        if(etli.isSelected()){
            siparisler.put("Etli Ekmek", 50);
        }
        else{
            siparisler.remove("Etli Ekmek", 50);
        }
        if(kuş.isSelected()){
            siparisler.put("Kuşbaşı Pide", 40);
        }
        else{
            siparisler.remove("Kuşbaşı Pide", 40);
        }
        if(lahmacun.isSelected()){
            siparisler.put("Lahmacun", 40);
        }
        else{
            siparisler.remove("Lahmacun", 40);
        }
        if(ez.isSelected()){
            siparisler.put("Ezme", 30);
        }
        else{
            siparisler.remove("Ezme", 30);
        }
        if(köz.isSelected()){
            siparisler.put("Köz Patlıcan", 50);
        }
        else{
            siparisler.remove("Köz Patlıcan", 50);
        }
        if(sal.isSelected()){
            siparisler.put("Salata", 30);
        }
        else{
            siparisler.remove("Salata", 30);
        }
        if(ayran.isSelected()){
            siparisler.put("Ayran", 20);
        }
        else{
            siparisler.remove("Ayran", 20);
        }
        if(kola.isSelected()){
            siparisler.put("Kola", 20);
        }
        else{
            siparisler.remove("Kola", 20);
        }
        if(salgam.isSelected()){
            siparisler.put("Şalgam", 20);
        }
        else{
            siparisler.remove("Şalgam", 20);
        }
        EkranaYazdir();
    }//GEN-LAST:event_hesaplaActionPerformed

    private void közActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_közActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_közActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiparişUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiparişUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiparişUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiparişUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiparişUygulaması().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox acilirMenü;
    private javax.swing.JCheckBox ayran;
    private javax.swing.JCheckBox etli;
    private javax.swing.JCheckBox ez;
    private javax.swing.JButton hesapla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox kaşarli;
    private javax.swing.JCheckBox kola;
    private javax.swing.JCheckBox kuş;
    private javax.swing.JCheckBox köz;
    private javax.swing.JCheckBox lahmacun;
    private javax.swing.JCheckBox sal;
    private javax.swing.JCheckBox salgam;
    private javax.swing.JLabel secilen;
    private javax.swing.JLabel toplam;
    // End of variables declaration//GEN-END:variables
}
